theme: jekyll-theme-minimal
title: Portfolio
description: A showcase of John Daciuk's projects
logo: [https://media-exp1.licdn.com/dms/image/C4E03AQHbdWwpAwTLTQ/profile-displayphoto-shrink_400_400/0?e=1602115200&v=beta&t=xSMT1LApO4yky_X9PLCIAyF6tvnBaMAcfy2j4jjmXpU]
