theme: jekyll-theme-minimal
title: Portfolio
description: John Daciuk is currently earning a M.S. in Computer Science from Columbia University and is expected to graduate December 2020.  Before joining Columbia John studied Computer Science at the Harvard Extension School.  John also holds a Masters in Teaching and has tutored over 800 students for the SAT, ACT, A.P. Calculus and Physics.
logo: me2.png
